#spring:
#  datasource:
#    username: root
#    password: 123
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis:
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*Mapper.xml
#  # 搜索指定包别名
#  type-aliases-package: com.eureka.client.provider.mapper
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis-config.xml
#
##showSql
#logging:
#  level:
#    com.isoftstone.demo.crud.dao: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/ #,http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 # 服务续约间隔，默认是30秒
    lease-expiration-duration-in-seconds: 10 # 服务失效时间 默认90秒

# 配置 路由追踪日志打印
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

spring:
  zipkin:
    #base-url: http://127.0.0.1:9411
    base-url: http://127.0.0.1:5672
    sender:
      #type: web #数据的传输方式，以http的形式向server端发送数据
      type: rabbit # 以rabbitmq的方式来实现异步传输
  sleuth:
    sampler:
      probability: 1 # 采样比，1是完全采样
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener: #设置请求重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true