server:
    port: 8000


spring:
    application:
        name: eureka-serverB

eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        # register-with-eureka: false #\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
        # fetch-registry: false #\u8868\u793A\u662F\u5426\u4ECE Eureka Server\u4E2D\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F, \u9ED8\u8BA4\u4E3Atrue, \u56E0\u4E3A\u8FD9\u662F\u4E00\u4E2A\u5355\u70B9\u7684 Eureka Server, \u4E0D\u9700\u8981\u540C\u6B65\u5176\u5B83\u7684 Eureka Server \u8282\u70B9\u7684\u6570\u636E\uFF0C \u6545\u800C\u8BBE\u7F6E\u4E3A false
        service-url:
            defaultZone: http://127.0.0.1:8000/eureka/ #,http://127.0.0.1:9000/eureka/  #\u914D\u7F6E\u66B4\u9732\u7ED9Eureka Client\u7684\u8BF7\u6C42\u5730\u5740

